#!/bin/bash
# Script de quick start para Hanami Analytics com Swagger

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         🚀 HANAMI ANALYTICS - QUICK START COM SWAGGER         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 ENDPOINTS PRINCIPAIS:"
echo ""
echo "  🌐 Dashboard:        http://localhost:5173"
echo "  📚 Swagger UI:       http://localhost:8000/docs           ⭐"
echo "  📖 ReDoc:            http://localhost:8000/redoc"
echo "  📋 OpenAPI Schema:   http://localhost:8000/openapi.json"
echo ""

echo "📦 ARQUIVOS DE DOCUMENTAÇÃO CRIADOS:"
echo ""
echo "  docs/"
echo "  ├── README.md                    (250 linhas) - Visão geral"
echo "  ├── INSTALLATION.md              (200 linhas) - Instalação"
echo "  ├── ARCHITECTURE.md              (300 linhas) - Arquitetura"
echo "  ├── API_DOCUMENTATION.md         (500+ linhas) - Endpoints"
echo "  ├── SWAGGER_GUIDE.md             (350 linhas) - Guia Swagger ⭐ NOVO"
echo "  ├── FRONTEND_DOCUMENTATION.md    (350 linhas) - Componentes"
echo "  ├── DATA_VALIDATION.md           (350 linhas) - Validação"
echo "  ├── TROUBLESHOOTING.md           (350 linhas) - Problemas"
echo "  └── INDEX.md                     (400+ linhas) - Índice ⭐ NOVO"
echo ""

echo "✨ NOVIDADES:"
echo ""
echo "  ✅ Swagger UI integrado em main.py"
echo "  ✅ Documentação detalhada em SWAGGER_GUIDE.md"
echo "  ✅ Contact info e metadados da API configurados"
echo "  ✅ Servidores (desenvolvimento e produção) definidos"
echo "  ✅ README.md com referências a Swagger"
echo "  ✅ API_DOCUMENTATION.md com links para Swagger"
echo "  ✅ INDEX.md como mapa de navegação da documentação"
echo ""

echo "🎯 COMEÇAR:"
echo ""
echo "  1. Inicie Backend:   cd api && python main.py"
echo "  2. Inicie Frontend:  cd frontend && npm run dev"
echo "  3. Abra Swagger:     http://localhost:8000/docs"
echo "  4. Teste endpoint:   POST /upload (escolha arquivo CSV)"
echo "  5. Leia docs:        docs/SWAGGER_GUIDE.md"
echo ""

echo "📚 ÍNDICE COMPLETO: docs/INDEX.md"
echo ""
echo "════════════════════════════════════════════════════════════════"
